### ISSUE TITLE
i don't know its an error or got wrong config

### ISSUE THREAD

**Issue by foxrider1998** [rubiksCoders/Login-Authentication-App#1]
![Cuplikan layar dari 2022-07-06 16-26-55](https://user-images.githubusercontent.com/78159283/177518327-46204bc8-3b5f-4f8d-9b89-47c8e4f1bebd.png)

got this eror ehen running

**Comment by mahendrasaikumargandham** [comment]
You imported the code in wrong way 
Firstly install two main dependencies
1. npm install @react-navigation/native
2. npm install @react-navigation/native-stack

and import 
import { NavigationContainer } from '@react-navigation/native';
import { createNativeStackNavigator } from '@react-navigation/native-stack';

Please check @foxrider1998

**Comment by foxrider1998** [comment]
thanks its work 🙏🙏🙏
